CREATE TABLE USER(
                     id INT PRIMARY KEY AUTO_INCREMENT,
                     username VARCHAR(20) DEFAULT NULL,
                     PASSWORD VARCHAR(32)
)

    INSERT INTO USER VALUES(NULL,'Tom','123123')
    INSERT INTO USER VALUES(NULL,'Jerry','123123')
