#端口号
server:
  port: 8300

#服务注册名称
spring:
  application:
    name: member-server
  #数据库相关配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.16.163.76:3306/dbtest?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: hhyu
    password: Yhh920205
    type: com.alibaba.druid.pool.DruidDataSource

#注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/